version: "3"
services: 
    api:
      image: alisafaa4/fastapi-project
      depends_on:
          - postgres
      ports:
          - 100:10000
      # command: bash -c "alembic upgrade head"
      # command: uvicorn app.main:app --host 0.0.0.0 --port 10000 --reload
      # env_file: 
      #   - ./.env
      environment:
        - DATABASE_HOSTNAME = ${DATABASE_HOSTNAME}
        - DATABASE_PORT = ${DATABASE_PORT}
        - DATABASE_PASSWORD = ${DATABASE_PASSWORD}
        - DATABASE_NAME = ${DATABASE_NAME}
        - DATABASE_USERNAME = ${DATABASE_USERNAME}
        - SECRET_KEY = ${SECRET_KEY} 
        - ALGORITHM = ${ALGORITHM}
        - ACCESS_TOKEN_EXPIRE_MINUTES = ${ACCESS_TOKEN_EXPIRE_MINUTES}

    postgres:
      image: postgres
      environment:
        - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        - POSTGRES_DB=${DATABASE_NAME}

      volumes:
          - postgres-db:/var/lib/postgresql/data



volumes: 
  postgres-db: